name: RepoTracker
on:
  schedule:
    - cron: "0 0 * * 0"
 
  watch:
    types: [started]
  
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: update
      run: |
        pip install requests
        python RepoTracker/update.py ${{ secrets.TOKEN }}
    - name: push      
      run: |
        git config --global user.name 'ChristophKirst'
        git config --global user.email 'christoph.kirst.ck@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add -A
        git commit -m "automatic count views"
        git push
